name: Recurring INT tests
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *' # every other hour

permissions:
  contents: read

jobs:
  int-tests:
    name: int tests
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Canary test
      uses: docker://ghcr.io/step-security/integration-test/int:latest
      env:
        PAT: ${{ secrets.PAT }}
        canary: true
