name: Recurring INT tests
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *' # every other hour

permissions:
  id-token: write
  contents: read

jobs:
  int-tests:
    name: int tests
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Canary test
      uses: docker://ghcr.io/step-security/integration-test/int:latest
      env:
        PAT: ${{ secrets.PAT }}
        canary: true

  int-tls-tests:
    name: int tls tests
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Canary test
      uses: docker://ghcr.io/step-security/integration-test/int:latest
      env:
        PAT: ${{ secrets.PAT }}
        canary-tls: true
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}
        AWS_REGION: ${{ env.AWS_REGION }}
        BUCKET: "s3-step-integration-tests-001"
        API_KEY: ${{ secrets.TENANT_API_KEY_PS }}
        WEBHOOK_URL: "https://webhook.site/0cfaf008-1a8b-46c0-a4e9-4dec5f9c3718"
        WEBHOOK_API_KEY: ${{ secrets.WEBHOOK_API_KEY }}
        WEBHOOK_TOKEN_ID: "0cfaf008-1a8b-46c0-a4e9-4dec5f9c3718"
